name: Start new game

on:
  workflow_dispatch:
  discussion:
    types: [locked]

jobs:
  new_game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start new game
        run: python3 main.py
      - name: Upload fen and README.md files
        uses: actions/upload-artifact@v4
        with:
          name: game
          path: |
            fen
            chess.md

  new_discussion:
    needs: [new_game]
    runs-on: ubuntu-latest
    permissions:
       discussions: write
       contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create a new GitHub Discussion
      id: create-discussion
      uses: abirismyname/create-discussion@v1.2.0
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: 'Chess Game'
        body-filepath: '/home/runner/work/community-chess/community-chess/game/chess.md'
        repository-id: ${{ secrets.REPOSITORY_ID }}
        category-id: ${{ secrets.CATEGORY_ID }}
    - name: Print discussion URL
      run: |
        echo discussion-url: ${{steps.create-discussion.outputs.discussion-url}}